apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator-lab
  template:
    metadata:
      labels:
        app: simulator-lab
    spec:
      containers:
      - name: axion-data-simulator
        image: akacr1212134.azurecr.io/axion-data-simulator:v2          
        ports:
        -  containePort: 8000
        


