apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ing
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: simulator.cloudpunk.shop
    http:
      paths:
      - backend:
          service:
            name: simulator-ser
            port:
              number: 80
        path: "/"
        pathType: Prefix

      